development:
  s3:
    bucket_name: 'nplol'
    access_key_id:  'AKIAINDFPYLGX72BJS5Q'
    secret_access_key:  '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'
  google:
    client_id: '636455440074-nceplif7r2ldtnhdsg8dsi56ee1bmof3.apps.googleusercontent.com'
    client_secret: '3tmxLdHliZ5GE7EDiuHxf0It'
  twitter:
    api_key: '91BVCERF4bBowgea6UIIWermY'
    secret: 'pGCCxCXtUf2gbjwLcWBBu2aSK6nM8abCwn3k0qNupXxyzGzEyQ'
  github:
    api_key: '73428824525ffc47bf0e'
    secret:  '15d8ff66b3201fa5d8f78450dfefdc7c2e7f4476'

production:
  s3:
    bucket_name: 'nplol'
    access_key_id:  'AKIAINDFPYLGX72BJS5Q'
    secret_access_key:  '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'
  google:
    client_id: '636455440074-nceplif7r2ldtnhdsg8dsi56ee1bmof3.apps.googleusercontent.com'
    client_secret: '3tmxLdHliZ5GE7EDiuHxf0It'
  twitter:
    api_key: '91BVCERF4bBowgea6UIIWermY'
    secret: 'pGCCxCXtUf2gbjwLcWBBu2aSK6nM8abCwn3k0qNupXxyzGzEyQ'
  github:
    api_key: '06405ce7e76a819b538d'
    secret:  '01235c8d6babd4e57815d131217187c135dfc2dd'
