development:
  s3:
    bucket_name: 'nplol'
    access_key_id:  'AKIAINDFPYLGX72BJS5Q'
    secret_access_key:  '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'
  google:
    client_id: '636455440074-nio4408qk70ljb3fb1aeo46qru34ckkd.apps.googleusercontent.com'
    client_secret: '4tzfqrBBSlNeaboabHFPNys_'
